### ISSUE TITLE
MVP Train/Tune 

### ISSUE THREAD

**Issue by kschelonka** [AllenInstitute/croissant#12]
The goal of this story is to get the basic code and tests in place for training a ML model for the ROI classification task. It is not to develop a "good" model or offer many different configuration features.

Create `train.py` script that:

* Loads input data (df/F, metadata, ROIs) and calls methods to generate features
* Feature processing methods:
    * One-hot-encode categorical vars with more than 2 values
* Trains model using:
    * Logistic regression with elastic net regularization
    * 5-fold CV optimizing for AUC, grid search
* Logs metrics, parameters, and tags to local MLFlow storage; artifacts also saved to local file storage
* Saves finished model to MLFlow Model format

**Validation Criteria**:
Can train a model on the development data packaged in the repo, and save it using MLFlow Model format. Can use the MLFlow model to generate label predictions on test data packaged in the repo.

See [design doc](http://confluence.corp.alleninstitute.org/pages/viewpage.action?pageId=80278240) for more info.

**Comment by isaak-willett** [comment]
This is still blocked until #20 is merged but I'm going ahead and starting on it and I'll rebase when that is merged, so the feature generation work is blocked but not data loading.
