### ISSUE TITLE
Classifier feature evaluation/engineering

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#27]
How far can we get with logistic regression improvements in 2 days?

Tasks:
- [ ] train classifier with current coded features
- [ ] generate presentation output
- [ ] Investigate feature improvements (time-boxed to maximum of 2 developer days)

Acceptance criteria:
- [ ] Presentation output of current features
- [ ] branch with new features from this effort
- [ ] presentation output of new features
- [ ] includes description of what has been added and why
- [ ] Notebooks used for this should be saved to persistent storage somewhere

**Comment by djkapner** [comment]
merged output manifest and test/train data with example scripts for creation are here:
`s3://prod.slapp.alleninstitute.org/merged_2line_2project`
