### ISSUE TITLE
Classifier feature engineering incorporating neuropil traces

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#45]
Similar to #40, time-boxed effort to investigate potential logistic regression improvements incorporating neuropil traces as an additional input data stream.

Tasks:
- [x] train classifier with current coded features
- [ ] generate presentation output
- [x] Investigate feature improvements (time-boxed to maximum of 1 developer day)

Acceptance criteria:
- [ ] Presentation output of current features
- [ ]  branch with new features from this effort
- [ ]  includes description of what has been added and why
- [ ]  Notebooks used for this should be saved to persistent storage somewhere

**Comment by kschelonka** [comment]
Additional task: Need to upload raw traces + neuropil traces to s3 for all training data

**Comment by kschelonka** [comment]
This is blocked until we incorporate methods for creating neuropil traces for the data we used for labeling.

**Comment by kschelonka** [comment]
I redid the models with the trace features coming from the neuropil-subtracted trace, resulting in slight improvement. Not sure if significant. However from the discussion yesterday it seems like the scientists do not want to use the trace data anymore.

**Comment by wbwakeman** [comment]
Choosing not to continue with this based on recent feedback from the scientific stakeholders.
