### ISSUE TITLE
Consider removing `full_genotype` and `targeted_structure` fields from consideration of classifier

### ISSUE THREAD

**Issue by njmei** [AllenInstitute/croissant#54]
Currently the FeatureExtractor (and classifier model) expect a very specific set of values for `full_genotype` and `targeted_structure` due to the OneHot encoded nature of those fields.

This will lead to a model that is not generalizeable. For example, if an experiment is performed on a new rig or an experiment is performed in a targeted_structure that the model has not been trained on.

**Comment by wbwakeman** [comment]
This probably overlaps with #57 .
