### ISSUE TITLE
Feature extractor should probably check for (and deal with) NaN values when computing features

### ISSUE THREAD

**Issue by njmei** [AllenInstitute/croissant#55]
In the case I encountered there was a `trace_skew` value that turned out to be `NaN` when processing `ophys_experiment_id`: 867410514

Example problematic trace files:

`/allen/scratch/aibstemp/nicholasm/programs/braintv/production/neuralcoding/prod0/specimen_834902199/ophys_session_867027875/ophys_experiment_867410514/processed/neuropil_traces.h5`

`/allen/scratch/aibstemp/nicholasm/programs/braintv/production/neuralcoding/prod0/specimen_834902199/ophys_session_867027875/ophys_experiment_867410514/processed/roi_traces.h5`

**Comment by njmei** [comment]
Example problematic trace files:

/allen/scratch/aibstemp/nicholasm/programs/braintv/production/neuralcoding/prod0/specimen_834902199/ophys_session_867027875/ophys_experiment_867410514/processed/neuropil_traces.h5

**Comment by wbwakeman** [comment]
NaNs turned out to be because existing extract traces generated these in old pipeline.  The Suite2p-based pipeline should never generate these.  If we do see them, then this should fail.
