### ISSUE TITLE
Investigate cell matching and train classifier using current production data

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#70]
From discussions with stakeholders, there may be value in training a model based on the existing production data.  The value here is that there is potentially a LOT of data available for training.  We need to be certain that there will be enough overlap between ROIs identified by current production and Suite2P to allow classification of the Suite2P ROIs.

Tasks:
- [x] Create a function to perform cell matching between Suite2P and production ROIs
- [x] Validate cell matching; report numbers of matched/not-matched
- [x] Make a decision to move forward based on above results, or not.
- [ ] Make a function that can queue up a production experiment for the feature extractor
- [ ] Identify some experiments to try this on initially

Acceptance criteria:
- [x] Report performance of cell matching
- [ ] If decide to move forward with it, then report performance of a model trained with the production data

**Comment by djkapner** [comment]
Reported this effort in meeting with science team on 9/17/2020.
Science team consensus seems to be to not do this and instead continue to manually annotate.
