### ISSUE TITLE
Train model based on 500 ROI Slc labeling job

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#73]
Based on the output from the labeling job for 500 Slc ROIs, need to train the classification model using the new data.

Tasks:
- [x] Ingest data to S3
- [x] Add methods to repo (annotation df)  Consider other areas for streamlining this process
- [x] Create new train and test splits
- [x] Rerun training
- [ ] Make plots to demo the results

Validation:
- [ ] Demo results to stakeholders

**Comment by kschelonka** [comment]
This is blocked until we get final decision from stakeholders about the segmentation quality + parameters.

**Comment by wbwakeman** [comment]
Doing this work revealed that we may need to do additional work on the features to address the changes in ROI shape after recent segmentation changes.  Will close this issue and open another story to do targeted training and additional feature engineering.
