### ISSUE TITLE
Targeted training and feature engineering for Slc set

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#78]
After the labeling results were evaluated for the 500-ROI Slc labeling job, we see that the significant features have changed.  This issue is to investigate and understand the new feature space.

Tasks:
- [x] Kat post a link in this issue to Leonard's features
- [x] Create initial feature importance plot
- [x] Investigate and summarize the labeler agreement for this set
- [x] Manual inspection of ROI shapes to generate feature ideas
- [x] Engineer features for improved performance

Validation criteria:
- [x] An improved classifier
OR
- [ ] An explanation for why it is not improved

**Comment by kschelonka** [comment]
Bulk of the old [method](http://stash.corp.alleninstitute.org/projects/INF/repos/lims2_modules/browse/CAM/ophys_detect/detectTemporal.cpp#780) (requires vpn) -- may need to noodle around in the repo to find more

See [newsletter](https://alleninstitute.sharepoint.com/:w:/s/Pika/EQ7kcb-7Rj5Dmk1SCFhxjyIB00iwh7VycIDx4BPTWcjpJQ?e=o549AH) for feature importance plot and data summary

**Comment by kschelonka** [comment]
I think we decided to add to this that @aamster will be exploring a CNN model, possibly initialized with CaImAn model weights.
I have been in communication with him about the data and am happy to pair/work together on updating any data engineering methods to get the required inputs
