### ISSUE TITLE
Report classifier progress to stakeholders

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#79]
Need to present the current state of classifier and features based on the recent 500-ROI Slc labeling effort

Tasks:
- [x] Send a summary message to stakeholders (all Newsletter recipients) regarding the current state of features and classifier as we begin to analyze the outputs from the labeling job
- [x] Generate reports in preparation for a meeting with the stakeholders
- [x] Have a meeting and record feedback

Validation criteria:
- [x] Documented feedback from the group

**Comment by djkapner** [comment]
In-progress doc:
https://alleninstitute.sharepoint.com/:w:/s/Pika/EQ7kcb-7Rj5Dmk1SCFhxjyIB00iwh7VycIDx4BPTWcjpJQ?e=muSrG3
