### ISSUE TITLE
Make curve of model performance versus amount of data using existing labeled data

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#84]
It would be valuable to see how using more data affects the training of the classifier model.  We could use the existing existing labeled ROIs set to generate this curve.

Tasks:
- [x] Generate a number of models using different amounts of data
- [x] Generate learning curve

Validation criteria:
- [x] provide learning curve plot (x = amount of data, y = performance)

**Comment by aamster** [comment]
I produced the learning curve using the current transfer learning model. The metric used is F1 (harmonic mean of precision and recall), and the model was evaluated using 5-fold cross validation. The training F1 and CV F1 are compared. 

The learning curve is not how I would have expected it to look. Generally the performance on the training set starts near perfect and decreases towards the optimum as more data is added. The validation performance usually starts out low and converges towards the training performance. The final gap between train/CV performance tells you if adding more data would help.

According to the plot, the model is robust against different data sizes, and performs about the same regardless. Furthermore, the validation performance is better than the train performance, which tells us that the model may not have enough capacity. Also the train/val performance nearly overlap, so it seems to indicate the model is underfit.

![learning_curve.png](https://images.zenhubusercontent.com/5fa1b163d87c6f82dfbeed1a/08454a2f-914e-4602-9bb7-d7528bd7ff50)
