### ISSUE TITLE
just-in-time labeling job(s) and visualizations

### ISSUE THREAD

**Issue by wbwakeman** [AllenInstitute/croissant#87]
From December classification conversations with stakeholders, we have agreed to do a targeted labeling job(s) for improvement of specific problem cases for the classifier.  Output is visualizations for review by team and stakeholders.

Tasks:
- [x] Create labeling job(s) for refinement of labeling
- [x] Combine new labels with existing data set
- [x] Retrain the CNN classifier
- [x] Report performance
- [x] Generate inference plots and summary statistics

Validation criteria:
- [ ] outputs provided to stakeholders

**Comment by djkapner** [comment]
content from Marina:
```
Natalia and I went through a bunch of plots for ROIs that were invalid with dev but valid for prod and sorted them into cell, not cell, and unsure:
\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_invalid_prod_valid
Those could be candidates for annotation, or you could feed them into the classifier directly if you think thats an ok thing to do
to be more specific, Natalia first sorted into the subfolders, then i went through and confirmed or modified the classification. so there were 2 sets of eyes on each plot, which is effectively a 2/3 consensus annotation
i was going to do the same for dev valid, prod invalid
the goal being to identify unambiguous cell vs not cell examples. which explains why there are so many in the 'unsure' category.
```
@matchings moving this conversation here in case this come to fruition Wednesday or Thursday or we can't remember in January.

**Comment by matchings** [comment]
i will share a .csv with cell IDs for these cases shortly

**Comment by matchings** [comment]
Natalia, Kate and I went through a set of plots for ROIs where the new classifier and the production classifier disagreed on whether it was a cell or not, and manually reclassified them into "definitely_cell" and "definitely_not_cell". 

.csv files with cell_roi_ids for each group are at the locations listed below. 

cells: 
"\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\definitely_cell_examples.csv"

not cells: 
"\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\definitely_not_cell_examples.csv"

**Comment by djkapner** [comment]
We think that Scott's labeling job with 300 ROIs will be completed in the next few days. I think it makes sense to wait for those and then retrain with:
* Marina + Natalia : 226 ROIs (128 cells, 98 not cells)
* Scott's curated 300 ROIs (breakdown unknown yet)
@danielsf @aamster this means, if not tomorrow, then W, Th, when I will already be on break. Do you have enough information to make artifacts and retrain?

**Comment by matchings** [comment]
not that its a huge difference, but i believe there are 128 cells and 125 not cells (rather than 98 not cells as listed above)

**Comment by danielsf** [comment]
I plan to be working on Wednesday, but not Thursday.

That being said, I am confident that, given a list of `ophys_experiment_id` and (Dev pipeline) `roi_id`, I can generate artifacts. That does not appear to be what is in these csvs. The only column is `cell_roi_id`. I assume this is the ROI's ID in the Production pipeline? If so, I can use Dan's cell matching dataframe to convert them into the appropriate Dev pipeline columns.

**Comment by matchings** [comment]
yes, cell_roi_id, is the production ROI id. I will remake those .csvs to include the dev roi_id and ophys_experiment_id.

**Comment by danielsf** [comment]
Don't feel like that's a blocker (I just wanted to make absolutely sure I wasn't misidentifying anything), but thank you.

**Comment by aamster** [comment]
@djkapner could you also help with getting the output manifest of the labeling job -- I'm not sure how it is generated.
@matchings -- just curious, are you saying that 125 / 253 production cells you reviewed were false positives?

**Comment by djkapner** [comment]
> could you also help with getting the output manifest of the labeling job -- I'm not sure how it is generated.

from the Sagemaker console, you can click on a job and see this info:
![image.png](https://images.zenhubusercontent.com/5dddcc4206735a0001da84bb/17aef141-2fbc-4d35-a403-4c7896352e81)

Follow the s3 link for output dataset location.

For a completed job, you'll find the output manifest at `<output dataset location>/manifests/output/output.manifest`

for an incomplete job, that s3 object does not exist yet.

**Comment by matchings** [comment]
@aamster here are some stats for what we reviewed: 

out of 302 ROIs that we reviewed where dev said they were not cells, but production said the were cells, 118 were false negatives, i.e. they were actually cells

out of 200 ROIs where dev said it was a cell, but production said it was not a cell, 27 were false positives, i.e. they were actually not cells 

you can see examples of our sorting in the sub-folders of these directories: 

\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_invalid_prod_valid 

\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_valid_prod_invalid

**Comment by aamster** [comment]
@matchings I'm a little confused. The 2 csvs (definitely_cell and definitely_not_cell) add up to 253 examples. Which 502 are you referring to above?

I'm trying to get a sense for how well production performs relative to a ground truth.

**Comment by matchings** [comment]
i'll step though it more carefully.

first, i identified several categories based on the output of matching dev ROIs to prod ROIs, and whether dev or prod called those ROIs valid cells or invalid (not cells). these categories are:
 
dev_valid_prod_valid (agreement - that's good)
dev_invalid_prod_invalid (also agreement) 
dev_valid_prod_invalid (disagreement between pipelines, suggestive of false positives in dev) 
dev_invalid_prod_valid (disagreement between pipelines, suggestive of false negatives in dev)

We took the two categories where there was disagreement and visually identified which of the ones that dev called valid were actually invalid (not cells), and which of the ones that dev called invalid were actually valid cells. 3 different experts viewed and agreed on these judgement calls. 

For dev_valid_prod_invalid, we started with 202 examples, in this folder: 
\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_valid_prod_invalid

And identified that 27 of those 202 were definitely_not_cells, which are false positives given that dev said they were valid cells. Those examples were copied to this folder: 
\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_valid_prod_invalid\definitely_not_cell

For dev_invalid_prod_valid, we started with 352 examples, in this folder: 
\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_invalid_prod_valid

And identified that 118 of those 352 were actually definitely_cell, which are false negatives given that dev said they were invalid (not cells). Those examples are in this folder: 
\\allen\programs\braintv\workgroups\nc-ophys\visual_behavior\qc_plots\classifier_validation\last_ditch_effort_annotation\classification_threshold_0.4\dev_invalid_prod_valid\definitely_cell 

So based on this exercise, the false positive rate is 27/202 = 13.4%, and the false negative rate is 118/352 = 33.5% 

This is in agreement with the general impression of the science team after looking at the dev classifier output that it was not identifying all the cells that it should have been.

**Comment by aamster** [comment]
@matchings thanks for providing the extra details. Here are the metrics that I calculated. 

dev_valid_prod_valid (these I am considering TP for both models): 798
dev_invalid_prod_invalid (these I am considering TN for both models): 392
I added these counts to both models when comparing them.

Dev:
Precision = TP / (TP + FP) = 973 / (973 + 27) = .97
Recall = TP / (TP + FN) = = 973 / (973 + 118) = .89

Production:
Precision = 916 / (916 + 234) = .79
Recall = 916 / (916 + 175) = .84

Please let me know if there is an error in this.

I think it is important that we compare both production and dev to a ground truth so that we can make a comparison of the models to determine which one is better. Currently we are comparing dev to production, but from this analysis, it is clear that production is far from error-free, so I don't see how making that comparison gives us good insight into how well dev is performing.

Also, if you agree, we should align on the same metrics. Typically in ML we use precision and recall as it measures performance better when there is class imbalance and we care about correctly predicting the positive class.

About estimating performance -- it is important to reserve a labeled test set to estimate performance. I want to be able to retrain the model, then estimate performance again, and get a sense for whether we improved performance or not. We currently estimate performance against 30% of the data, but it seemed that analysis was not too helpful for the science team to judge performance. Is there a dataset which we can use to measure performance before and after to test whether performance improved or not? Do you trust using the 30% held out test set?

**Comment by aamster** [comment]
Performance decreased after adding additional examples. Hypotheses for this:

- This increases the size of the test set and so we get a better estimate of performance
- The added examples are difficult for the model to classify

![pr_curve_comparison.png](https://images.zenhubusercontent.com/5fa1b163d87c6f82dfbeed1a/b14024b1-5643-40bf-a629-8a140c2da229)

**Comment by wbwakeman** [comment]
Okay to leave off the following given the reported performance hit and the decision on direction from just before the break.  Thanks everyone for working on this.

> Generate inference plots and summary statistics
> Validation criteria:
>  outputs provided to stakeholders
